language: python

python:
  - "2.7"

sudo : required

before_install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls
#  - pip install nose
#  - pip install mock
  
script: 
   - cd source
   - export PYTHONPATH=$PYTHONPATH:$(pwd)
   - cd ../tests
   - coverage -m run nose.core test_serial.py test_register.py --omit= */site-packages/*
   - nosetests --with-coverage -v

after_success:
   - coveralls

