language: python

python:
  - "2.7"

sudo : required

before_install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls
#  - pip install nose
#  - pip install mock
  
script: 
   - cd source
   - export PYTHONPATH=$PYTHONPATH:$(pwd)
   - cd ../tests
   - nosetests -v --with-coverage --cover-tests --cover-package=source tests 

after_success:
   - coveralls --rcfile=.coveragerc

