language: python

python:
  - "2.7"

sudo: required

before_install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls
  - pip install nose
  - pip install mock
  
  


install:
  - python setup.py install

after_success:
  - coveralls

