language: python

python:
  - "2.7"

sudo: required

before_install:
  - pip install coverage
  - pip install python-coveralls
  - pip install nose
  - pip install mock
  
script:
  - nosetests --with-coverage -v

after_success:
  - coveralls

