language: python

python:
  - "2.7"

sudo: required

before_install:
  - pip install coverage
  - pip install python-coveralls
  - pip install nose
  - pip install mock
  
script: python tests/test_register.py

after_success:
  - coveralls

